name: Build SparkleShare (Simple)

on:
  push:
    branches: [ main, master, develop ]
    tags: [ 'v*' ]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      
    - name: Create missing images (if needed)
      run: |
        if (-not (Test-Path "SparkleShare\Linux\Images\icons\hicolor")) {
          New-Item -Path "SparkleShare\Linux\Images\icons\hicolor" -ItemType Directory -Force
          Copy-Item "SparkleShare\Windows\Images\folder.png" "SparkleShare\Linux\Images\icons\hicolor\document-added-12.png" -ErrorAction SilentlyContinue
          Copy-Item "SparkleShare\Windows\Images\folder.png" "SparkleShare\Linux\Images\icons\hicolor\document-deleted-12.png" -ErrorAction SilentlyContinue
          Copy-Item "SparkleShare\Windows\Images\folder.png" "SparkleShare\Linux\Images\icons\hicolor\document-edited-12.png" -ErrorAction SilentlyContinue
          Copy-Item "SparkleShare\Windows\Images\folder.png" "SparkleShare\Linux\Images\icons\hicolor\document-moved-12.png" -ErrorAction SilentlyContinue
          Copy-Item "SparkleShare\Windows\Images\process-syncing.png" "SparkleShare\Linux\Images\icons\hicolor\process-working-22.png" -ErrorAction SilentlyContinue
        }
        
    - name: Restore NuGet packages
      run: nuget restore SparkleShare.sln
      
    - name: Build Sparkles Core
      run: msbuild Sparkles/Sparkles.csproj /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
      
    - name: Build Sparkles Git
      run: msbuild Sparkles/Git/Sparkles.Git.csproj /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
      
    - name: Build Windows Application  
      run: msbuild SparkleShare/Windows/SparkleShare.Windows.csproj /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
      
    - name: Verify build output
      run: |
        Write-Host "=== Build Output Verification ==="
        if (Test-Path "bin\SparkleShare.Windows.exe") {
          Write-Host "✅ SparkleShare.Windows.exe created successfully"
          $exe = Get-Item "bin\SparkleShare.Windows.exe"
          Write-Host "   Size: $($exe.Length) bytes"
          Write-Host "   Created: $($exe.CreationTime)"
        } else {
          Write-Host "❌ SparkleShare.Windows.exe NOT FOUND"
          Write-Host "Contents of bin directory:"
          Get-ChildItem bin -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "   $_" }
          exit 1
        }
        
        Write-Host "=== All files in bin directory ==="
        Get-ChildItem bin -Recurse -ErrorAction SilentlyContinue | Select-Object Name, Length | Format-Table
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: SparkleShare-Windows-Build
        path: bin/
        retention-days: 30

  create-release:
    name: Create Release Package
    runs-on: windows-latest
    needs: build-windows
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: SparkleShare-Windows-Build
        path: bin/
        
    - name: Create release package
      run: |
        # Create release folder
        New-Item -Path "SparkleShare-Package" -ItemType Directory -Force
        Copy-Item "bin\*" "SparkleShare-Package\" -Recurse -Force
        
        # Create launcher
        $launcher = @'
        @echo off
        title SparkleShare - File Synchronization
        echo.
        echo ==========================================
        echo   SparkleShare with Bug Fixes Applied
        echo ==========================================
        echo.
        echo Starting SparkleShare...
        cd /d "%~dp0"
        
        if exist "SparkleShare.Windows.exe" (
            start "" "SparkleShare.Windows.exe"
            echo.
            echo SparkleShare has been launched!
            echo Look for the SparkleShare icon in your system tray.
            echo.
            timeout /t 3 >nul
        ) else (
            echo ERROR: SparkleShare.Windows.exe not found!
            echo Make sure all files were extracted properly.
            pause
        )
        '@
        $launcher | Out-File -FilePath "SparkleShare-Package\Launch-SparkleShare.bat" -Encoding ASCII
        
        # Create README
        $readme = @"
        # SparkleShare ${{ github.ref_name }} - Windows Release
        
        **A secure file synchronization tool with critical bug fixes applied.**
        
        ## Quick Start
        1. Run ``Launch-SparkleShare.bat`` (recommended)
        2. Or double-click ``SparkleShare.Windows.exe``
        3. Follow the setup wizard
        4. Check your system tray for the SparkleShare icon
        
        ## Bug Fixes in This Version
        - ✅ **Thread Safety**: Fixed dangerous Thread.Abort() usage
        - ✅ **Memory Leaks**: Fixed crypto object disposal
        - ✅ **SSH Connectivity**: Dynamic port handling
        - ✅ **File Operations**: Fixed file existence checks  
        - ✅ **Resource Management**: Proper disposal patterns
        - ✅ **Error Handling**: Better exception management
        - ✅ **Process Stability**: No more unexpected exits
        - ✅ **Windows Compatibility**: Improved Git command execution
        
        ## System Requirements
        - Windows 7 or later (Windows 10/11 recommended)
        - .NET Framework 4.8
        - Git for Windows (recommended)
        
        ## Support
        Report issues: https://github.com/hbons/SparkleShare/issues
        
        ---
        Built: $(Get-Date -Format "yyyy-MM-dd HH:mm") UTC
        Version: ${{ github.ref_name }}
        "@
        $readme | Out-File -FilePath "SparkleShare-Package\README.md" -Encoding UTF8
        
        # Create ZIP
        $version = "${{ github.ref_name }}" -replace "^v", ""
        Compress-Archive -Path "SparkleShare-Package\*" -DestinationPath "SparkleShare-Windows-$version.zip" -Force
        
        Write-Host "✅ Release package created: SparkleShare-Windows-$version.zip"
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "SparkleShare ${{ github.ref_name }}"
        body: |
          ## SparkleShare ${{ github.ref_name }} for Windows
          
          **A stability and security focused release with 8 critical bug fixes.**
          
          ### 🔥 Key Improvements
          - 🛡️ Enhanced security and thread safety
          - 🚀 Better stability and error handling  
          - 🔧 Improved Windows compatibility
          - 🌐 Enhanced SSH connectivity
          
          ### 📦 Download & Install
          1. Download `SparkleShare-Windows-${{ github.ref_name }}.zip`
          2. Extract to your preferred location
          3. Run `Launch-SparkleShare.bat`
          
          ### 🎯 System Requirements
          - Windows 7+ (.NET Framework 4.8)
          - Git for Windows (recommended)
          
          This release includes comprehensive fixes for thread safety, memory management, file operations, and Windows-specific compatibility issues.
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
        files: SparkleShare-Windows-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}