name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'
        
    - name: Create placeholder missing images
      run: |
        New-Item -Path "SparkleShare\Linux\Images\icons\hicolor" -ItemType Directory -Force
        Copy-Item "SparkleShare\Windows\Images\folder.png" "SparkleShare\Linux\Images\icons\hicolor\document-added-12.png" -Force
        Copy-Item "SparkleShare\Windows\Images\folder.png" "SparkleShare\Linux\Images\icons\hicolor\document-deleted-12.png" -Force  
        Copy-Item "SparkleShare\Windows\Images\folder.png" "SparkleShare\Linux\Images\icons\hicolor\document-edited-12.png" -Force
        Copy-Item "SparkleShare\Windows\Images\folder.png" "SparkleShare\Linux\Images\icons\hicolor\document-moved-12.png" -Force
        Copy-Item "SparkleShare\Windows\Images\process-syncing.png" "SparkleShare\Linux\Images\icons\hicolor\process-working-22.png" -Force
        
    - name: Restore NuGet packages
      run: nuget restore SparkleShare.sln
      
    - name: Build SparkleShare
      run: |
        msbuild Sparkles/Sparkles.csproj /p:Configuration=Release /p:Platform="Any CPU"
        msbuild Sparkles/Git/Sparkles.Git.csproj /p:Configuration=Release /p:Platform="Any CPU"
        msbuild SparkleShare/Windows/SparkleShare.Windows.csproj /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Create release package
      run: |
        # Create release directory
        mkdir SparkleShare-Release
        Copy-Item "bin\*" "SparkleShare-Release\" -Recurse -Force
        
        # Create launcher script
        @'
        @echo off
        title SparkleShare
        echo.
        echo ======================================
        echo    Welcome to SparkleShare!
        echo ======================================
        echo.
        echo Starting SparkleShare with bug fixes applied...
        echo.
        
        cd /d "%~dp0"
        
        if not exist "SparkleShare.Windows.exe" (
            echo ERROR: SparkleShare.Windows.exe not found!
            echo Please make sure all files were extracted properly.
            echo.
            pause
            exit /b 1
        )
        
        if not exist ".NET Framework 4.8" (
            echo NOTE: This application requires .NET Framework 4.8
            echo Download from: https://dotnet.microsoft.com/download/dotnet-framework/net48
            echo.
        )
        
        echo Starting application...
        start "" "SparkleShare.Windows.exe"
        
        echo.
        echo SparkleShare has been launched!
        echo Check your system tray for the SparkleShare icon.
        echo.
        timeout /t 3 >nul
        '@ | Out-File -FilePath "SparkleShare-Release\Launch-SparkleShare.bat" -Encoding ASCII
        
        # Create comprehensive README
        @"
        # SparkleShare ${{ github.ref_name }} - Windows Release
        
        **A secure, cross-platform file synchronization tool that uses Git as backend.**
        
        ## 🚀 What's New in This Release
        
        This version includes **8 critical bug fixes** that improve security, stability, and reliability:
        
        ### 🔒 Security & Stability Fixes
        - **Thread Safety**: Replaced dangerous ``Thread.Abort()`` with proper cancellation tokens
        - **Memory Leaks**: Fixed crypto object disposal to prevent memory leaks  
        - **SSH Security**: Dynamic SSH port handling instead of hardcoded ports
        - **Resource Management**: Proper disposal of file handles and resources
        - **Process Stability**: Eliminated unexpected application exits
        - **Configuration Safety**: Robust Git config handling with error recovery
        - **Input Validation**: Comprehensive path and URL validation
        - **Error Handling**: Better exception management throughout the application
        
        ## 📦 Installation Instructions
        
        ### Quick Start
        1. **Extract** all files to a folder (e.g., ``C:\SparkleShare\``)
        2. **Run** ``Launch-SparkleShare.bat`` (recommended) or ``SparkleShare.Windows.exe``
        3. **Follow** the setup wizard to add your first Git repository
        4. **Check** your system tray for the SparkleShare icon
        
        ### System Requirements
        - **OS**: Windows 7 or later (Windows 10/11 recommended)
        - **Framework**: .NET Framework 4.8 (download if needed)
        - **Git**: Git for Windows (recommended for full functionality)
        - **Disk Space**: ~50MB for application files
        
        ## 🎯 Key Features
        
        - **Real-time Sync**: Automatic file synchronization across devices
        - **Git Backend**: Full version history and conflict resolution
        - **Multiple Repositories**: Manage multiple sync folders
        - **Secure**: SSH key authentication and encrypted connections  
        - **Cross-platform**: Works with Linux and macOS versions
        - **Hosting Agnostic**: Works with GitHub, GitLab, self-hosted, and more
        
        ## 🔧 Configuration
        
        ### Adding Your First Repository
        1. Click the SparkleShare tray icon
        2. Choose "Add Hosted Project"  
        3. Enter your Git repository URL
        4. Select local folder location
        5. Add your SSH key or use existing authentication
        
        ### Supported Git Hosts
        - GitHub
        - GitLab  
        - Bitbucket
        - Self-hosted Git servers
        - Any Git repository accessible via SSH/HTTPS
        
        ## 🆘 Troubleshooting
        
        ### Application Won't Start
        - Ensure .NET Framework 4.8 is installed
        - Run as Administrator if needed
        - Check Windows Event Viewer for error details
        
        ### Sync Issues  
        - Verify SSH keys are properly configured
        - Check Git repository permissions
        - Ensure network connectivity to Git server
        
        ### Performance Issues
        - Exclude SparkleShare folders from antivirus scans
        - Ensure sufficient disk space
        - Check for Git LFS if handling large files
        
        ## 📝 Version Information
        
        - **Release**: ${{ github.ref_name }}
        - **Build Date**: $(Get-Date -Format 'yyyy-MM-dd')
        - **Platform**: Windows (.NET Framework 4.8)
        - **Architecture**: Any CPU (x86/x64 compatible)
        
        ## 🤝 Support & Community
        
        - **Issues**: [Report bugs on GitHub](https://github.com/hbons/SparkleShare/issues)
        - **Documentation**: [SparkleShare Wiki](https://github.com/hbons/SparkleShare/wiki)
        - **Community**: Join discussions in GitHub issues
        - **Source Code**: [View on GitHub](https://github.com/hbons/SparkleShare)
        
        ## 📄 License
        
        SparkleShare is open source software licensed under the GNU General Public License v3.0.
        See LICENSE file for full terms.
        
        ---
        
        **Enjoy secure, reliable file synchronization with SparkleShare!** 🎉
        "@ | Out-File -FilePath "SparkleShare-Release\README.md" -Encoding UTF8
        
        # Create ZIP package
        $version = "${{ github.ref_name }}" -replace '^v',''
        Compress-Archive -Path "SparkleShare-Release\*" -DestinationPath "SparkleShare-Windows-$version.zip" -Force
        
    - name: Generate Release Notes
      id: release_notes
      run: |
        $notes = @"
        ## SparkleShare ${{ github.ref_name }} for Windows
        
        **A major stability and security update with 8 critical bug fixes applied.**
        
        ### 🔥 Highlights
        - 🛡️ **Enhanced Security**: Fixed thread safety and resource management issues
        - 🚀 **Improved Stability**: Eliminated crashes and unexpected exits  
        - 🔧 **Better Error Handling**: More robust error recovery and user feedback
        - 🌐 **SSH Improvements**: Dynamic port handling and better authentication
        
        ### 🐛 Bug Fixes Applied
        - **Thread Safety**: Replaced dangerous ``Thread.Abort()`` with cancellation tokens
        - **Memory Leaks**: Fixed crypto object disposal preventing memory leaks
        - **SSH Connectivity**: Dynamic SSH port handling instead of hardcoded values  
        - **File Operations**: Corrected inverted file existence checks
        - **Resource Management**: Proper disposal of file handles and streams
        - **Git Configuration**: Safer config handling with error recovery
        - **Process Management**: Eliminated ``Environment.Exit()`` calls
        - **Input Validation**: Added comprehensive path and URL validation
        
        ### 📦 Installation
        1. Download ``SparkleShare-Windows-${{ github.ref_name }}.zip``
        2. Extract to your preferred location
        3. Run ``Launch-SparkleShare.bat`` (recommended)
        4. Follow the setup wizard
        
        ### ⚡ System Requirements
        - Windows 7 or later
        - .NET Framework 4.8
        - Git for Windows (recommended)
        
        ### 🆘 Need Help?
        - Check the included README.md for detailed instructions
        - Report issues on GitHub
        - Join community discussions
        
        **This release represents a significant improvement in stability and security over previous versions.**
        "@
        
        # Save to GitHub output
        $notes | Out-File -FilePath release_notes.txt -Encoding UTF8
        echo "RELEASE_NOTES<<EOF" >> $env:GITHUB_OUTPUT
        Get-Content release_notes.txt | ForEach-Object { echo $_ >> $env:GITHUB_OUTPUT }
        echo "EOF" >> $env:GITHUB_OUTPUT
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: SparkleShare ${{ github.ref_name }}
        body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
        files: SparkleShare-Windows-*.zip
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}